_shared: &shared
  - 'docker-bake.hcl'
  - 'Taskfile.yml'
  - 'test/**'
  - '.github/workflows/bake_targets.yml'
pgvector:
  - 'pgvector/**'
  - *shared
postgis:
  - 'postgis/**'
  - *shared
pgaudit:
  - 'pgaudit/**'
  - *shared
pg-crash:
  - 'pg-crash/**'
  - *shared
