name: New Extension Proposal
description: Propose a new PostgreSQL extension to be included in the containers and commit to its maintenance.
title: "[New Extension]: "
labels: ["triage", "new-extension"]
projects: ["cloudnative-pg/postgres-extensions-containers"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new extension for the PostgreSQL Extensions Containers project!

        The submission process requires the proposer to commit to becoming the **Component Owner** and taking on the long-term maintenance of the extension image. Please review the [governance document for the submission process](https://github.com/cloudnative-pg/postgres-extensions-containers?tab=readme-ov-file#submission-process).

  - type: checkboxes
    id: search
    attributes:
      label: Is there an existing issue for this extension request?
      description: Before you submit a request, please **search existing issues** to ensure this extension hasn't already been proposed.
      options:
        - label: I have searched for an existing issue, and could not find a duplicate request.
          required: true

  - type: input
    id: extension-name
    attributes:
      label: Extension Name
      description: What is the official name of the PostgreSQL extension?
      placeholder: ex. pgvector
    validations:
      required: true

  - type: input
    id: project-url
    attributes:
      label: Project Repository URL
      description: The URL of the main source code repository (e.g., GitHub, GitLab).
      placeholder: ex. https://github.com/pgvector/pgvector
    validations:
      required: true

  - type: input
    id: website-url
    attributes:
      label: Extension Website URL (Optional)
      description: The URL of the official website or main documentation page.
      placeholder: ex. https://pgvector.io/
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Short Description
      description: A brief description of the extension and its primary use case.
      placeholder: ex. The pgvector extension provides vector similarity search capabilities for PostgreSQL.
    validations:
      required: true

  - type: input
    id: license-url
    attributes:
      label: Main LICENSE Link
      description: A direct link to the main license file in the repository (e.g., a link to the raw LICENSE file).
      placeholder: ex. https://github.com/pgvector/pgvector/blob/master/LICENSE
    validations:
      required: true

  - type: checkboxes
    id: license-check
    attributes:
      label: License Compliance
      description: Please confirm the license of the extension complies with the **allowed licenses** for this project.
      options:
        - label: The extension's license (linked above) complies with the list of allowed licenses.
          required: true

  - type: textarea
    id: dependent-extensions
    attributes:
      label: Known Dependent Extensions
      description: List any other PostgreSQL extensions that MUST be installed before or alongside this extension (e.g., if this extension requires 'plpgsql' or 'postgis' to be present). If none, please state "None".
      placeholder: ex. postgis
    validations:
      required: true

  - type: checkboxes
    id: maintenance-commitment
    attributes:
      label: Component Owner and Maintenance Commitment
      description: By checking this box, you confirm your commitment to the long-term maintenance of the extension image. This includes providing updates for new upstream versions, responding to security issues, and ensuring compatibility with new PostgreSQL/OS versions.
      options:
        - label: I/My organization commit to becoming the Component Owner and maintaining the extension image in the future.
          required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes (Optional)
      description: Any other relevant information, required dependencies (like OS packages), or context that might be useful for packaging.
      placeholder: ex. This extension requires the 'openssl' library (OS package) to be installed.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cloudnative-pg/governance/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
